### ISSUE TITLE
Excess seats

### ISSUE THREAD

**Issue by neistridlar** [gthaatar/UltimateShuttleIVA-FullRetro#15]
There appears to be 6 extra seats partially clipped inside the wall bellow the main deck. 
![screenshot582](https://user-images.githubusercontent.com/38767958/39621748-13894f72-4f90-11e8-88d1-64289106c0d4.png)

**Comment by gthaatar** [comment]
Indeed. I am intending these to be bunk beds until I care to find some actual ones.

Also, regarding the Overlay. At some point I intend to remove the stockoverlay and replace it with one that just clears out the windows. This is one because that'll just be cool. But also, because of how I had to build certain parts of the IVA, like the seat/beds here, I had to clip them. And with the overlay, you can see some of this clipping.  So I'm going to hide that.
