### ISSUE TITLE
Backseat

### ISSUE THREAD

**Issue by icetitan** [gthaatar/UltimateShuttleIVA-FullRetro#17]
![screenshot 8](https://user-images.githubusercontent.com/38858221/39637020-27da0020-4fc2-11e8-96aa-e4687e63095f.png)
All of the backseats are like this.

**Comment by gthaatar** [comment]
Yes, these are intentional. I had the idea to add in bunks for sleeping in the middeck (because honestly there isn't much I can think of/find to really fill the space without _just_ populating it with a bunch of random stuff.

This will probably change. I'm going to check NFprops for other stuff I could use here.
