### ISSUE TITLE
Verification_Analog FDAI Display 

### ISSUE THREAD

**Issue by debaker02** [gthaatar/UltimateShuttleIVA-FullRetro#2]
On my install it was too low to zoom in on well, i also ran into issues where if i used the digital buttons on the center top panel i could not get the analog item to work.

**Comment by gthaatar** [comment]
Are you referring to the FDAI itself or the controls? If its the controls, then that'll be fixed when I adjust the transforms in the model. The seat positions as I have them are a bit too far up on the controls, so you'd have to be zoomed out in order to look down due to limitations in how far the camera can move. 

And what are you referring to by the digital on the center top? MechJeb controller or the SAS?  Also not sure if you mean the clock or the NAV Radio by the analog item. 

One thing I've noticed is in order to use some of the SAS controls (such as lock Pro or Retrograde) you actually have to be in motion first.

**Comment by debaker02** [comment]
The Jeb controls on the middle top

**Comment by icetitan** [comment]
![window](https://user-images.githubusercontent.com/38858221/39428747-cf84feca-4c88-11e8-83fc-91bf95436fea.png)
The window  on the left side has a leak.

**Comment by gthaatar** [comment]
So I've played with it, and I can't for the life of me find any issues. I'm able to use all the central controls as well as the analog clock.

**Comment by debaker02** [comment]
Whatever it was its good now, i did what i did before.
