### ISSUE TITLE
Validation_Mixed Tech & Layout

### ISSUE THREAD

**Issue by debaker02** [gthaatar/UltimateShuttleIVA-FullRetro#5]
Hi,
Ok so this is totally up to you, but here is my input.  

You mixed techs in a way that would probably not be done.  In the pilots primary display area there is a FDAI and 8-Ball.  This does not mix with the Heads up display or MFD in the middle.  

In general you will have a Nav Display, then a Primary Flight display.  Then in the middle an engine display...but still and mfd.  The dash board is your control section to enable things like the autopilot...etc.

The center pedestal is where you have your communications management unit. 

![image](https://user-images.githubusercontent.com/16918893/39390614-23dd62f8-4a65-11e8-876a-c907cf8ec5ed.png)

I made a bad sketch

You can ignore all of this if its what you were going for now.

**Comment by gthaatar** [comment]
Well, the layout as designed is mostly based on this:

https://orig00.deviantart.net/b4c6/f/2011/364/e/f/space_shuttle_cockpit_by_kouglov-d4kpqqs.jpg

This is the actual layout that was used on the Shuttles prior to the glass cockpit upgrade. You'll notice it does in fact include both the FDAI and HSI (i believe you may have your terms confused. 8 ball is what the FDAI is nicknamed) in the positions I have them.

Right now, the MFD's are standins for the original CRT's. We do have a CRT prop available that would fit better, but I chose not to utilize it for now as its only configured to display a camera feed. If I can get the MFD's pages into the CRT (which I think may be possible, need to touch base with MoarDV on this one) then they'll be replaced.

And if you look here:

https://c1.staticflickr.com/4/3476/3361558523_7f5213360f_b.jpg

You'll find that a HUD is also present in the original cockpit.

On that note however, after finding this picture and seeing the pit a bit more clearly as a whole, I think I'm going to spread stuff out a bit more. I'm realizing now I got a little too fixated on the first print and didn't consider the actual real life spacing, which in turn caused the problem where I was running out of props to place because I packed them in so tightly, relatively speaking. 

So this means Comms will likely move to the center console like in the real pit, and in its place I'll put in an RCS hand control, which I can combine with the Docking controls to fill in that section.

**Comment by debaker02** [comment]
All sounds legit, I was not thinking about the shuttle.  Go with your vision!
